### ISSUE TITLE
Play 2.5 breaks seed

### ISSUE THREAD

**Issue by thetuyo** [adrianhurt/play-silhouette-credentials-seed#1]
I was trying to build this seed (with Silhouette 4.0 and Play 2.5) but it breaks a lot.  I'm aware that there are a few changes in 2.5.  Do you mind updating this seed so it can be used with Play 2.5 ? 

Thanks!

**Comment by adrianhurt** [comment]
Hi, I'll try it as soon as possible. As I see, the main changes comes from Silhouette 4.0 that is still beta.

**Comment by thetuyo** [comment]
thanks, I’ll watch for when you have updated it.

**Comment by thetuyo** [comment]
Great work on this seed.   So, I tried migrating it all day to silhouette 4.0 all day without luck in getting it to work.   Probably because my Play/Scala skills is not that great.    So watch for when you've updated it.    thanks.

**Comment by adrianhurt** [comment]
I'm so sorry for the loooong delay, @thetuyo. I've had too busy months since then. I've just updated the seed to Play 2.5 and Silhouette 4.

I've had to reimplement it almost from zero. My previous approach extending a custom `Environment` results now in difficulties to test it. And since now the DI is the preferred method in Play, I've decided to follow the "standard" way using DI and a module to provide all the required classes. However I think this seed still has a different approach than the official Silhouette example seed to simplify some things.
